# Generated by Django 4.1.3 on 2025-02-14 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_question_quiz_alter_quiz_creator'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['question_number']},
        ),
        migrations.RemoveField(
            model_name='question',
            name='option1',
        ),
        migrations.RemoveField(
            model_name='question',
            name='option2',
        ),
        migrations.RemoveField(
            model_name='question',
            name='option3',
        ),
        migrations.RemoveField(
            model_name='question',
            name='option4',
        ),
        migrations.AddField(
            model_name='question',
            name='options',
            field=models.JSONField(default=['Venus', 'Mars', 'Jupiter', 'Saturn']),
            preserve_default=False,
        ),
    ]
