# Generated by Django 4.1.3 on 2025-02-20 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_question_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='deadline',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
