export const QUIZ_LIST_REQUEST = 'QUIZ_LIST_REQUEST'
export const QUIZ_LIST_SUCCESS = 'QUIZ_LIST_SUCCESS'
export const QUIZ_LIST_FAIL = 'QUIZ_LIST_FAIL'

export const QUIZ_DETAILS_REQUEST = 'QUIZ_DETAIL_REQUEST'
export const QUIZ_DETAILS_SUCCESS = 'QUIZ_DETAIL_SUCCESS'
export const QUIZ_DETAILS_FAIL = 'QUIZ_DETAIL_FAIL'

export const QUIZ_CREATE_REQUEST = 'QUIZ_CREATE_REQUEST'
export const QUIZ_CREATE_SUCCESS = 'QUIZ_CREATE_SUCCESS'
export const QUIZ_CREATE_FAIL = 'QUIZ_CREATE_FAIL'

export const QUIZ_UPDATE_REQUEST = 'QUIZ_UPDATE_REQUEST' 
export const QUIZ_UPDATE_SUCCESS = 'QUIZ_UPDATE_SUCCESS'
export const QUIZ_UPDATE_FAIL = 'QUIZ_UPDATE_FAIL'

export const QUIZ_DELETE_REQUEST = 'QUIZ_DELETE_REQUEST'
export const QUIZ_DELETE_SUCCESS = 'QUIZ_DELETE_SUCCESS'
export const QUIZ_DELETE_FAIL = 'QUIZ_DELETE_FAIL'